### ISSUE TITLE
Please check this it simply does not work

### ISSUE THREAD

**Issue by michalss** [MammaMiaDev/avaloniaui-the-series#1]
HI,

Can you please check and test this example project ? I made exact copies of ViewLocator and App files, but it seems there is some issue wiyh Net8 and it does not work anymore.. yes i could have some mistake there but i dont think i did..

https://github.com/michalss/AvaloniaTestDependencyInjectionSimple.git

Thx a lot

**Comment by MammaMiaDev** [comment]
Hey @michalss, can you give me some more details about the error?

**Comment by erdemcan999** [comment]
I have a like that error. What is the solution?
![image](https://github.com/user-attachments/assets/72623bce-f502-41f8-a49d-63bdcd6f1566)
