### ISSUE TITLE
Missing NuGet package

### ISSUE THREAD

**Issue by Plootie** [MammaMiaDev/avaloniaui-the-series#2]
No package exists by the name `CommunityToolkit.Labs.Extensions.DependencyInjection` making this project impossible to build

**Comment by MammaMiaDev** [comment]
Hey! Thanks for the submission. That package comes from the [Community Toolkit Preview Packages](https://github.com/CommunityToolkit/WindowsCommunityToolkit/wiki/Preview-Packages) feed, you can find more info in [this video](https://www.youtube.com/watch?v=q6lFGr2DeHQ).

In my last commit I've added a `Nuget.Config` file with the feed required from the Labs package. Pull the latest changes from this repo, and you should be able to build and run the application. Make sure you've got dotnet 8 installed.

Let me know if it works.

**Comment by Plootie** [comment]
Sorry, Only just got a chance to look at this. Thanks for the update, works great ^^
